Changed data source from .csv to .db. Methods of reading data source …
denes-f/SkyrimAlchemyHelper pull request #3
Opened 2024-04-05 14:18 UTC by denes-f

…updated in skyrim_alchemy_helper.py

2024-04-05 14:45 UTC, farago-kristof requested changes

2024-04-05 14:45 UTC, farago-kristof commented on skyrim_alchemy_helper.py
> +        res = self._db_cursor.execute(f'SELECT Ingredient from {self._table_name} WHERE "{effect_name}" IN ("Primary Effect", "Secondary Effect", "Tertiary Effect", "Quaternary Effect")')
Don't use f strings in queries, use parametrization instead. 
https://docs.python.org/3/library/sqlite3.html
"Notice that ? placeholders are used to bind data to the query. Always use placeholders instead of [string formatting](https://docs.python.org/3/tutorial/inputoutput.html#tut-formatting) to bind Python values to SQL statements, to avoid [SQL injection attacks](https://en.wikipedia.org/wiki/SQL_injection) (see [How to use placeholders to bind values in SQL queries](https://docs.python.org/3/library/sqlite3.html#sqlite3-placeholders) for more details)."

2024-04-06 06:19 UTC, denes-f commented on skyrim_alchemy_helper.py
> +        res = self._db_cursor.execute(f'SELECT Ingredient from {self._table_name} WHERE "{effect_name}" IN ("Primary Effect", "Secondary Effect", "Tertiary Effect", "Quaternary Effect")')
Updated SQL queries to use parametrization instead of f strings.

2024-04-06 07:02 UTC, farago-kristof approved these changes

2024-04-06 07:05 UTC, merged